### PR TITLE
Allow non-alphanumeric characters in variables

### PR DESCRIPTION
**Pull request by tbitai**
I needed `*` as a variable, and as far as I understand, only whitespace and parentheses are special to the parsing, so I modified variable parsing to allow any character besides these.

### CODE REVIEW

**Comment by tbitai** [comment]
I just realized that comma is also special, excluded that, too.

**Comment by rkirsling** [comment]
Actually, comma isn't special, [remember](https://github.com/rkirsling/formula-parser/pull/1#issuecomment-185493724)? 😛 

You're right that parentheses and whitespace are the only distinguished symbols, so at first this seemed quite reasonable. Unfortunately, part of the idea behind defining variables as alphanumeric strings is that whitespace is only required to _separate_ alphanumeric strings.

Specifically, say you have a parser with binaries `+`, `*`, and `mod`.

Under the current behavior:
- `x mod y` is parsed as a binary subformula, `xmody` is parsed as a variable
- `x*y` is parsed identically to `x * y`, as a binary subformula
- `+*+` throws a `SyntaxError`

With your change, `_parseVariable` becomes voraciously greedy:
- `x mod y` is parsed as a binary subformula, `xmody` is parsed as a variable
- `x * y` is parsed as a binary subformula, `x*y` is parsed **as a variable**
- `+*+` **parses as a variable**

While it might be nice to have the flexibility to parse, for instance, functional [kind](https://en.wikipedia.org/wiki/Kind_%28type_theory%29) syntax like `* -> * -> *`, I'm afraid this is probably just one of those things to turn to a full-fledged CFG parser generator for...

**Comment by tbitai** [comment]
Ouch :blush: I'm using this for a side project, so my memory is incomplete about it... Thanks for pointing this out!

I made two mistakes: 1) I remembered incorrectly that comma was part of the library, 2) I forgot about operator symbols. Comma is one of my operator symbols, that's why I noticed that I should exclude it from variables, but actually every operator symbol should be excluded. Now I thought this through properly, and I see that I handled everything now: the library parses variables that are connected with operators, so of course variable symbols cannot contain operator symbols, plus there's whitespace and parentheses, which also cannot be contained in variables; and that's it.

However, there's one difference in this from the current behavior (besides that it allows non-alphanupmeric characters in variables): operator symbols containing only alphanumeric characters that are not surrounded by whitespaces will be parsed as operator symbols (as any other kind of operator symbol). That is, from your example, `xmody` will be parsed as a binary subformula. I don't know if any of your users wants this to be parsed as a variable; I don't, and actually I think it's more natural like this, think `x*y` vs `xRy` for example, with `*` and `R` being binary operators: these are currently parsed differently.

**Comment by rkirsling** [comment]
I appreciate the effort, but I'm afraid this just isn't the intended behavior here. 😓

Broadly speaking, if you take a programming language where `x mod y` is valid (say, OCaml), it's quite natural and expected that `xmody` will be parsed as a variable.

More crucially, your latest change prohibits variable names from containing an alphanumeric operator as a substring: if `mod` is a binary operator, then `mode` is an illegal variable name. Yet just because JavaScript has `x in y` doesn't mean I have to think twice about naming a variable `isLoading`.

It's possible, of course, to have a sound parser which interprets `xRy` as a binary subformula, but such a parser would presumably restrict the length and/or capitalization of identifiers. This is simple to achieve with a CFG parser generator, but is more flexibility than this "instructive" parser class is meant to have.

**Comment by tbitai** [comment]
Thanks for the explanation, I only had mathematical applications in mind, I didn't consider programming languages.

I still need `*` as a variable (actually as a constant, parsed as a variable, abusing the concept of variable in the suggested way :smile:), so I will go with my fork now.

**Pull request closed without merging**
